<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WpfAudioPlayer</RootNamespace>
    <AssemblyName>WpfAudioPlayer</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
